CREATE DATABASE PERSONALES
ON PRIMARY
(
	NAME = PERSONALES_Data,
	FILENAME = 'C:\DBI\PERSONALES.mdf',
	SIZE = 20MB,
	MAXSIZE = 70MB,
	FILEGROWTH = 10%
)

LOG ON
(
	NAME = PERSONALES_Log,
	FILENAME = 'C:\DBI\PERSONALES.ldf',
	SIZE = 10MB,
	MAXSIZE = 40MB,
	FILEGROWTH = 5MB
);