CREATE DATABASE COMERCIAL_JD
ON PRIMARY
(
	NAME = COMERCIAL_JD_Data,
	FILENAME = 'C:\DBI\COMERCIAL_JD_mdf',
	SIZE = 20MB,
	MAXSIZE = 70MB,
	FILEGROWTH = 5MB
)

LOG ON
(
	NAME = COMERCIAL_JD_Log,
	FILENAME = 'C:\DBI\COMERCIAL_JD_ldf',
	SIZE = 10MB,
	MAXSIZE = 40MB,
	FILEGROWTH = 5MB
);
DROP DATABASE COMERCIAL_JD;
GO