USE PERSONALES2
GO

CREATE TABLE PAISES
(

CodPais INT IDENTITY (1,1) NOT NULL,

Name_Pais VARCHAR(50) NOT NULL,

Gentilicio_Pais VARCHAR(50) NOT NULL,

CONSTRAINT Pk_Pais PRIMARY KEY CLUSTERED (CodPais)

) 

ON TABLAS; 

CREATE SCHEMA Ventas; 

CREATE TABLE Ventas.Ciudades
(

CodPais INT NOT NULL, 

CodCiudad INT NOT NULL DEFAULT 0,

Name_Ciudad VARCHAR(50) NOT NULL,

CONSTRAINT PK_Ciudad PRIMARY KEY CLUSTERED (CodPais, CodCiudad),
CONSTRAINT FK_Ciudad_Pais FOREIGN KEY (CodPais)
REFERENCES dbo.PAISES(CodPais)

) 

ON TABLAS; 

DROP TABLE Ventas.Ciudades; 
DROP TABLE dbo.PAISES;