USE PERSONALES
GO

CREATE TABLE PAIS
(
	CodPais INT IDENTITY(1,1) NOT NULL,
	NombrePais VARCHAR(50) NOT NULL,
	Gentilicio VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Pais PRIMARY KEY CLUSTERED (CodPais)

)
ON TABLAS;

CREATE SCHEMA Ventas;

CREATE TABLE Ventas.Cuidad
(
	CodPais INT NOT NULL,
	CodCuidad INT NOT NULL DEFAULT 0,
	NombreCuidad VARCHAR(50) NOT NULL,
	CONSTRAINT PK_Cuidad PRIMARY KEY CLUSTERED (CodPais,CodCuidad),
	CONSTRAINT FK_Cuidad_Pais FOREIGN KEY (CodPais) REFERENCES dbo.PAIS(CodPais)

)
ON TABLAS;


DROP TABLE Ventas.Cuidad;
DROP TABLE PAIS;
